version: '3.2'

networks:
  ostenet:

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - URL=localhost.nip.io #osteklokken.morell.site
      - SUBDOMAINS=api
      - VALIDATION=http
      - EMAIL=tobiasmorell@hotmail.com #optional
    volumes:
      - ./nginx/letsencrypt-conf:/config
    networks:
      - ostenet
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped


  kollektiv-backend:
    build: OsteklokkenServer
    volumes:
    - ./users:/app/users
    - ./db:/app/db
    - ./public:/app/public
    networks:
      - ostenet
    ports:
      - 1001:5000

  preact-frontend:
    build: .
    networks:
      - ostenet
    ports:
      - 1000:80